time_intervals:
  - "10:00-12:00"
  - "13:00-15:00"
  - "17:00-19:00"
  - "21:00-22:00"
messages:
  end_enabled:
    - "§r"
    - "§x§F§F§9§B§0§0§l⎛  §f§k123§f  §x§F§F§A§5§0§0≪§x§F§F§B§4§0§0Э§x§F§F§C§2§0§0н§x§F§F§D§1§0§0д§x§F§F§D§F§0§0е§x§F§F§E§E§0§0р§x§F§F§D§F§0§0-§x§F§F§D§1§0§0М§x§F§F§C§2§0§0и§x§F§F§B§4§0§0р§x§F§F§A§5§0§0≫ §f§k123"
    - "§x§F§F§9§B§0§0§l⎥   §fСейчас §6открыт§f и доступен до §a§n{END_TIME}§f"
    - "§x§F§F§9§B§0§0§l⎝   §fУспей §bзалутать§f лут §6первым§f!"
    - "§r"
  end_disabled:
    - "§r"
    - "§x§F§F§9§B§0§0§l⎛   §f§k123§f  §x§F§F§A§5§0§0≪§x§F§F§B§4§0§0Э§x§F§F§C§2§0§0н§x§F§F§D§1§0§0д§x§F§F§D§F§0§0е§x§F§F§E§E§0§0р§x§F§F§D§F§0§0-§x§F§F§D§1§0§0М§x§F§F§C§2§0§0и§x§F§F§B§4§0§0р§x§F§F§A§5§0§0≫ §f§k123"
    - "§x§F§F§9§B§0§0§l⎥   §fСейчас §6закрыт§f и будет доступен в §a§n{NEXT_OPENING_TIME}§f"
    - "§x§F§F§9§B§0§0§l⎝   §fДождитесь §bследуйщего§f уведомления об §aоткрытии§f!"
    - "§r"
  teleport_message:
    - "§r"
    - "§x§F§F§9§B§0§0§l⎛                 §x§F§F§A§5§0§0≪§x§F§F§B§4§0§0Э§x§F§F§C§2§0§0н§x§F§F§D§1§0§0д§x§F§F§D§F§0§0е§x§F§F§E§E§0§0р§x§F§F§D§F§0§0-§x§F§F§D§1§0§0М§x§F§F§C§2§0§0и§x§F§F§B§4§0§0р§x§F§F§A§5§0§0≫"
    - "§x§F§F§9§B§0§0§l⎥   §fСейчас §6закрыт§f и вы §6телепортированы§f на спавн."
    - "§x§F§F§9§B§0§0§l⎝   §fДождитесь §bследуйщего§f уведомления об §aоткрытии§f!"
    - "§r"
teleport_world: "spawn"
teleport_coordinates:
  x: 100.0
  y: 65.0
  z: 200.0
  yaw: 90.0
  pitch: 45.0
